[General]
showlogo=hidden
showClock=true
logo=/usr/share/pixmaps/fluxos/fluxos-logo.png
type=image
color=#1d99f3
fontSize=10
background=/usr/share/pixmaps/fluxos/fluxos-wallpaper.png
needsFullUserModel=false
